# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

create_grants:
	$(MAKE) -C ../cdk create_grants
	
revoke_grants:
	$(MAKE) -C ../cdk revoke_grants

revoke_walter_grant:
	$(MAKE) -C ../cdk revoke_walter_grant

revoke_faythe_grant:
	$(MAKE) -C ../cdk revoke_faythe_grant

list_grants:
	$(MAKE) -C ../cdk list_grants
